tools:
  php_code_sniffer:
    config:
      standard: WordPress
  sensiolabs_security_checker: true
build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
checks:
  php:
    avoid_closing_tag: false
    avoid_superglobals: false
    coding_standard:
      name: WordPress
    no_exit: false
    no_global_keyword: false
    one_class_per_file: false
    psr2_class_declaration: false
    psr2_control_structure_declaration: false
    psr2_switch_declaration: false
    variable_existence: false
    verify_access_scope_valid: false
    verify_argument_usable_as_reference: false
    verify_property_names: false
filter:
  dependency_paths:
     - wordpress/
  excluded_paths:
    - languages/
    - tests/
